name: "test" 

on: [push]

jobs: 
  test-build:
    runs-on: ubuntu-latest

    steps:
        #este action especifico es para salir del archivo y ubicarnos en la carpeta de todo el repositorio
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: ls
        run: | #comando para scripts multilinea
         chmod +x script.sh
         ./script.sh