name: "test" 

on: [push]

jobs: 
  test-build:
    runs-on: ubuntu-latest

    #para configurar variables de entorno
    env:
      MY_VAR: variable

    steps:
        #este action especifico es para salir del archivo y ubicarnos en la carpeta de todo el repositorio
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: a ver si esta script
        run: ls 

      - name: ls
        run: | #comando para scripts multilinea
         chmod +x script.sh
         ./script.sh

      - name: my action
        uses: ./.github/Actions/My-action
        with:
          message: "juan"

      - name: probarvariable
        run: echo "hola mi variable $MY_VAR"

      - name: probarvariablerepo
        run: echo "hola mi variable ${{ vars.MY_VAR2 }}"