name: "hola mundo github actions"

on: [push] #evento

jobs: 
  hola:
    runs-on: ubuntu-latest #dice en que servidor vamos a correr el job

    steps:
    - name: Hola mundo
      run: echo "Hola mundo"

  other:
    runs-on: ubuntu-latest #dice en que servidor vamos a correr el job

    steps:
    - name: ls
      run: ls -al
